language: node_js

node_js: 
  - 9.2.1

sudo: required

services:
  - docker

before_install:
  - docker build -t jacksontchristo/adverts:v0 .
  - docker push jacksontchristo/adverts:v0
  - docker swarm init
  - docker stack deploy -c docker-compose.yml adverts
  - docker exec $(sudo docker container ls -f 'name=adverts_web' -q) node_modules/.bin/knex migrate:latest
  - docker exec $(sudo docker container ls -f 'name=adverts_web' -q) node_modules/.bin/knex seed:run

script:
  - npm run test

after_success:
  - echo YAY