language: node_js

node_js: 
  - 9.2.1

sudo: required

services:
  - docker

before_install:
  - docker build -t jacksontchristo/adverts:v0 .
  - docker run -p 80:80 -d jacksontchristo/adverts:v0

script:
  - npm run test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker jacksontchristo/adverts:v0;
    fi