language: node_js

node_js: 
  - 9.2.1

sudo: required

services:
  - docker

before_install:
  - docker build -t jacksontchristo/adverts:v0 .
  - docker login -u jacksontchristo -p ${DOCKER_PASSWORD}
  - docker push jacksontchristo/adverts:v0
  - docker swarm init
  - docker stack deploy -c docker-compose.yml adverts
  - sleep 10
  - docker network inspect adverts_webnet
  - docker exec $(sudo docker container ls -f 'name=adverts_web' -q) sh -c 'echo $NODE_ENV'
  - docker exec $(sudo docker container ls -f 'name=adverts_web' -q) sh -c 'node_modules/.bin/knex migrate:latest'
  - docker exec $(sudo docker container ls -f 'name=adverts_web' -q) sh -c 'node_modules/.bin/knex seed:run'

script:
  - npm run test

after_success:
  - echo YAY