version: "3"
services:
  web:
    image: jacksontchristo/adverts:v0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: