version: "3"
services:
  web:
    image: jacksontchristo/adverts:v0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: test
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "80:80"
    networks:
      - webnet
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: adverts
    ports:
      - ${POSTGRES_PORT-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata: