version: "3"
services:
  web:
    image: jacksontchristo/adverts:v0
    deploy:
      replicas: 8
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: docker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NEWRELIC_KEY: ${NEWRELIC_KEY}
    ports:
      - "80:80"
    networks:
      - webnet
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: adverts
    ports:
      - ${POSTGRES_PORT-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata: